// <auto-generated />
using System;
using Data_Acces_Layer.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acceso_BD.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Acceso_BD.Repository.Entity.Debilidades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DebilidadId")
                        .HasColumnType("int");

                    b.Property<int>("IdTipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdTipo");

                    b.ToTable("Debilidades");
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.Fortalezas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EficazId")
                        .HasColumnType("int");

                    b.Property<int>("IdTipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdTipo");

                    b.ToTable("Fortalezas");
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.ModificadorTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BonusId")
                        .HasColumnType("int");

                    b.Property<int>("IdTipo")
                        .HasColumnType("int");

                    b.Property<int>("Modificador")
                        .HasColumnType("int");

                    b.Property<int>("TipoBonusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BonusId");

                    b.ToTable("Modificadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdTipo = 1,
                            Modificador = 1,
                            TipoBonusId = 2
                        },
                        new
                        {
                            Id = 2,
                            IdTipo = 1,
                            Modificador = 0,
                            TipoBonusId = 3
                        });
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.Pokedex", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("ID"), 1L, 1);

                    b.Property<string>("Altura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Basico")
                        .HasColumnType("bit");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Peso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<int?>("StatId")
                        .HasColumnType("int");

                    b.Property<int?>("TierId")
                        .HasColumnType("int");

                    b.Property<int?>("ZonaId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RegionId");

                    b.HasIndex("StatId");

                    b.HasIndex("TierId")
                        .IsUnique()
                        .HasFilter("[TierId] IS NOT NULL");

                    b.HasIndex("ZonaId");

                    b.ToTable("Pokedex");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Basico = true,
                            Nombre = "Bulbasaur",
                            RegionId = 1,
                            TierId = 1,
                            ZonaId = 1
                        },
                        new
                        {
                            ID = 2,
                            Basico = false,
                            Nombre = "Ivysaur",
                            RegionId = 1,
                            ZonaId = 2
                        },
                        new
                        {
                            ID = 3,
                            Basico = false,
                            Nombre = "Venasaur",
                            RegionId = 2,
                            TierId = 4,
                            ZonaId = 2
                        },
                        new
                        {
                            ID = 4,
                            Basico = true,
                            Nombre = "Charmander",
                            ZonaId = 1
                        },
                        new
                        {
                            ID = 5,
                            Basico = false,
                            Nombre = "Charmeleon",
                            ZonaId = 2
                        },
                        new
                        {
                            ID = 6,
                            Basico = false,
                            Nombre = "Charizard "
                        },
                        new
                        {
                            ID = 7,
                            Basico = true,
                            Nombre = "Squirtle"
                        },
                        new
                        {
                            ID = 8,
                            Nombre = "Wartotle"
                        },
                        new
                        {
                            ID = 9,
                            Nombre = "Blastoise"
                        },
                        new
                        {
                            ID = 10,
                            Nombre = "Caterpie",
                            ZonaId = 1
                        },
                        new
                        {
                            ID = 11,
                            Nombre = "Metapod"
                        },
                        new
                        {
                            ID = 12,
                            Nombre = "Butterfree"
                        },
                        new
                        {
                            ID = 13,
                            Nombre = "Weedle",
                            ZonaId = 2
                        },
                        new
                        {
                            ID = 14,
                            Nombre = "Kakuna"
                        },
                        new
                        {
                            ID = 15,
                            Nombre = "Beedril"
                        },
                        new
                        {
                            ID = 16,
                            Nombre = "Pidgey"
                        },
                        new
                        {
                            ID = 17,
                            Nombre = "Pidgeotto"
                        },
                        new
                        {
                            ID = 18,
                            Nombre = "Pidgeot"
                        },
                        new
                        {
                            ID = 19,
                            Nombre = "Rattata"
                        },
                        new
                        {
                            ID = 20,
                            Nombre = "Raticat"
                        },
                        new
                        {
                            ID = 21,
                            Nombre = "Spearow"
                        },
                        new
                        {
                            ID = 22,
                            Nombre = "Fearow"
                        },
                        new
                        {
                            ID = 23,
                            Nombre = "Ekans"
                        },
                        new
                        {
                            ID = 24,
                            Nombre = "Arbok"
                        },
                        new
                        {
                            ID = 25,
                            Nombre = "Pikachu"
                        },
                        new
                        {
                            ID = 26,
                            Nombre = "Raichu"
                        },
                        new
                        {
                            ID = 27,
                            Nombre = "Sandshrew"
                        },
                        new
                        {
                            ID = 28,
                            Nombre = "Sandslah"
                        },
                        new
                        {
                            ID = 29,
                            Nombre = "Nidoran ♀"
                        },
                        new
                        {
                            ID = 30,
                            Nombre = "Nidorina"
                        },
                        new
                        {
                            ID = 31,
                            Nombre = "Nidoqueen"
                        },
                        new
                        {
                            ID = 32,
                            Nombre = "Nidoran ♂"
                        },
                        new
                        {
                            ID = 33,
                            Nombre = "Nidorino"
                        },
                        new
                        {
                            ID = 34,
                            Nombre = "Nidoking"
                        },
                        new
                        {
                            ID = 35,
                            Nombre = "Clefairy"
                        },
                        new
                        {
                            ID = 36,
                            Nombre = "Clefable"
                        },
                        new
                        {
                            ID = 37,
                            Nombre = "Vulpix"
                        },
                        new
                        {
                            ID = 38,
                            Nombre = "Ninetales"
                        },
                        new
                        {
                            ID = 39,
                            Nombre = "Jigglypuff"
                        },
                        new
                        {
                            ID = 40,
                            Nombre = "Wigglytuff"
                        },
                        new
                        {
                            ID = 41,
                            Nombre = "Zubat"
                        },
                        new
                        {
                            ID = 42,
                            Nombre = "Golbat"
                        },
                        new
                        {
                            ID = 43,
                            Nombre = "Oddish"
                        },
                        new
                        {
                            ID = 44,
                            Nombre = "Gloom"
                        },
                        new
                        {
                            ID = 45,
                            Nombre = "Vileplume"
                        },
                        new
                        {
                            ID = 46,
                            Nombre = "Paras"
                        },
                        new
                        {
                            ID = 47,
                            Nombre = "Parasect"
                        },
                        new
                        {
                            ID = 48,
                            Nombre = "Venonat"
                        },
                        new
                        {
                            ID = 49,
                            Nombre = "Venomoth"
                        },
                        new
                        {
                            ID = 50,
                            Nombre = "Diglett"
                        },
                        new
                        {
                            ID = 51,
                            Nombre = "Dugtrio"
                        },
                        new
                        {
                            ID = 52,
                            Nombre = "Meowth"
                        },
                        new
                        {
                            ID = 53,
                            Nombre = "Persian"
                        },
                        new
                        {
                            ID = 54,
                            Nombre = "Psyduck"
                        },
                        new
                        {
                            ID = 55,
                            Nombre = "Golduck"
                        },
                        new
                        {
                            ID = 56,
                            Nombre = "Mankey"
                        },
                        new
                        {
                            ID = 57,
                            Nombre = "Primeape"
                        },
                        new
                        {
                            ID = 58,
                            Nombre = "Growlithe"
                        },
                        new
                        {
                            ID = 59,
                            Nombre = "Arcanine"
                        },
                        new
                        {
                            ID = 60,
                            Nombre = "Poliwag"
                        },
                        new
                        {
                            ID = 61,
                            Nombre = "Poliwhirl"
                        },
                        new
                        {
                            ID = 62,
                            Nombre = "Poliwrath"
                        },
                        new
                        {
                            ID = 63,
                            Nombre = "Abra"
                        },
                        new
                        {
                            ID = 64,
                            Nombre = "Kadabra"
                        },
                        new
                        {
                            ID = 65,
                            Nombre = "Alakazam"
                        },
                        new
                        {
                            ID = 66,
                            Nombre = "Machop"
                        },
                        new
                        {
                            ID = 67,
                            Nombre = "Machoke"
                        },
                        new
                        {
                            ID = 68,
                            Nombre = "Machamp"
                        },
                        new
                        {
                            ID = 69,
                            Nombre = "Bellsprout"
                        },
                        new
                        {
                            ID = 70,
                            Nombre = "Weepinbell"
                        },
                        new
                        {
                            ID = 71,
                            Nombre = "Victreebell"
                        },
                        new
                        {
                            ID = 72,
                            Nombre = "Tentacool"
                        },
                        new
                        {
                            ID = 73,
                            Nombre = "Tentacruel"
                        },
                        new
                        {
                            ID = 74,
                            Nombre = "Geodude"
                        },
                        new
                        {
                            ID = 75,
                            Nombre = "Graveler"
                        },
                        new
                        {
                            ID = 76,
                            Nombre = "Golem"
                        },
                        new
                        {
                            ID = 77,
                            Nombre = "Ponyta"
                        },
                        new
                        {
                            ID = 78,
                            Nombre = "Rapidash"
                        },
                        new
                        {
                            ID = 79,
                            Nombre = "Slowpoke"
                        },
                        new
                        {
                            ID = 80,
                            Nombre = "Slowbro"
                        },
                        new
                        {
                            ID = 81,
                            Nombre = "Magnemite"
                        },
                        new
                        {
                            ID = 82,
                            Nombre = "Magneton"
                        },
                        new
                        {
                            ID = 83,
                            Nombre = "Farfetch'd"
                        },
                        new
                        {
                            ID = 84,
                            Nombre = "Doduo"
                        },
                        new
                        {
                            ID = 85,
                            Nombre = "Dodrio"
                        },
                        new
                        {
                            ID = 86,
                            Nombre = "Seel"
                        },
                        new
                        {
                            ID = 87,
                            Nombre = "Dewgong"
                        },
                        new
                        {
                            ID = 88,
                            Nombre = "Grimer"
                        },
                        new
                        {
                            ID = 89,
                            Nombre = "Muk"
                        },
                        new
                        {
                            ID = 90,
                            Nombre = "Shellder"
                        },
                        new
                        {
                            ID = 91,
                            Nombre = "Cloyster"
                        },
                        new
                        {
                            ID = 92,
                            Nombre = "Gastly"
                        },
                        new
                        {
                            ID = 93,
                            Nombre = "Haunter"
                        },
                        new
                        {
                            ID = 94,
                            Nombre = "Gengar"
                        },
                        new
                        {
                            ID = 95,
                            Nombre = "Onix"
                        },
                        new
                        {
                            ID = 96,
                            Nombre = "Drowzee"
                        },
                        new
                        {
                            ID = 97,
                            Nombre = "Hypno"
                        },
                        new
                        {
                            ID = 98,
                            Nombre = "Krabby"
                        },
                        new
                        {
                            ID = 99,
                            Nombre = "Kingler"
                        },
                        new
                        {
                            ID = 100,
                            Nombre = "Voltorb"
                        },
                        new
                        {
                            ID = 101,
                            Nombre = "Electrode"
                        },
                        new
                        {
                            ID = 102,
                            Nombre = "Exeggcute"
                        },
                        new
                        {
                            ID = 103,
                            Nombre = "Exeggutor"
                        },
                        new
                        {
                            ID = 104,
                            Nombre = "Cubone"
                        },
                        new
                        {
                            ID = 105,
                            Nombre = "Marowak"
                        },
                        new
                        {
                            ID = 106,
                            Nombre = "Hitmonlee"
                        },
                        new
                        {
                            ID = 107,
                            Nombre = "Hitmonchan"
                        },
                        new
                        {
                            ID = 108,
                            Nombre = "Lickitung"
                        },
                        new
                        {
                            ID = 109,
                            Nombre = "Koffing"
                        },
                        new
                        {
                            ID = 110,
                            Nombre = "Weezing"
                        },
                        new
                        {
                            ID = 111,
                            Nombre = "Rhyhorn"
                        },
                        new
                        {
                            ID = 112,
                            Nombre = "Rhydon"
                        },
                        new
                        {
                            ID = 113,
                            Nombre = "Chansey"
                        },
                        new
                        {
                            ID = 114,
                            Nombre = "Tangela"
                        },
                        new
                        {
                            ID = 115,
                            Nombre = "Kangskhan"
                        },
                        new
                        {
                            ID = 116,
                            Nombre = "Horsea"
                        },
                        new
                        {
                            ID = 117,
                            Nombre = "Seadra"
                        },
                        new
                        {
                            ID = 118,
                            Nombre = "Goldeen"
                        },
                        new
                        {
                            ID = 119,
                            Nombre = "Seaking"
                        },
                        new
                        {
                            ID = 120,
                            Nombre = "Staryu"
                        },
                        new
                        {
                            ID = 121,
                            Nombre = "Starmie"
                        },
                        new
                        {
                            ID = 122,
                            Nombre = "Mr.Mime"
                        },
                        new
                        {
                            ID = 123,
                            Nombre = "Scyher"
                        },
                        new
                        {
                            ID = 124,
                            Nombre = "Jynx"
                        },
                        new
                        {
                            ID = 125,
                            Nombre = "Electabuzz"
                        },
                        new
                        {
                            ID = 126,
                            Nombre = "Magmar"
                        },
                        new
                        {
                            ID = 127,
                            Nombre = "Pinsir"
                        },
                        new
                        {
                            ID = 128,
                            Nombre = "Tauros"
                        },
                        new
                        {
                            ID = 129,
                            Nombre = "Magikarp"
                        },
                        new
                        {
                            ID = 130,
                            Nombre = "Gyarados"
                        },
                        new
                        {
                            ID = 131,
                            Nombre = "Lapras"
                        },
                        new
                        {
                            ID = 132,
                            Nombre = "Ditto"
                        },
                        new
                        {
                            ID = 133,
                            Nombre = "Eevee"
                        },
                        new
                        {
                            ID = 134,
                            Nombre = "Vaporeon"
                        },
                        new
                        {
                            ID = 135,
                            Nombre = "Jolteon"
                        },
                        new
                        {
                            ID = 136,
                            Nombre = "Flareon"
                        },
                        new
                        {
                            ID = 137,
                            Nombre = "Porygon"
                        },
                        new
                        {
                            ID = 138,
                            Nombre = "Omanyte"
                        },
                        new
                        {
                            ID = 139,
                            Nombre = "Omastar"
                        },
                        new
                        {
                            ID = 140,
                            Nombre = "Kabuto"
                        },
                        new
                        {
                            ID = 141,
                            Nombre = "Kabutops"
                        },
                        new
                        {
                            ID = 142,
                            Nombre = "Aerodactyl"
                        },
                        new
                        {
                            ID = 143,
                            Nombre = "Snorlax"
                        },
                        new
                        {
                            ID = 144,
                            Nombre = "Articuno"
                        },
                        new
                        {
                            ID = 145,
                            Nombre = "Zapdos"
                        },
                        new
                        {
                            ID = 146,
                            Nombre = "Moltres"
                        },
                        new
                        {
                            ID = 147,
                            Nombre = "Dratini"
                        },
                        new
                        {
                            ID = 148,
                            Nombre = "Dragonair"
                        },
                        new
                        {
                            ID = 149,
                            Nombre = "Dragonite"
                        },
                        new
                        {
                            ID = 150,
                            Nombre = "Mewtwo"
                        },
                        new
                        {
                            ID = 151,
                            Nombre = "Mew"
                        });
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.Region", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regiones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Kanto"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Johto"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Hoenn"
                        });
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.Tier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tiers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Basico"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Legendario"
                        });
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.Tipo", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("Tipo_pokemon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tipos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Tipo_pokemon = "Fuego"
                        },
                        new
                        {
                            Id = 2,
                            Tipo_pokemon = "Agua"
                        },
                        new
                        {
                            Id = 3,
                            Tipo_pokemon = "Planta"
                        },
                        new
                        {
                            Id = 4,
                            Tipo_pokemon = "Electrico"
                        },
                        new
                        {
                            Id = 5,
                            Tipo_pokemon = "Roca"
                        },
                        new
                        {
                            Id = 6,
                            Tipo_pokemon = "Acero"
                        },
                        new
                        {
                            Id = 7,
                            Tipo_pokemon = "Volador"
                        },
                        new
                        {
                            Id = 8,
                            Tipo_pokemon = "Hielo"
                        },
                        new
                        {
                            Id = 9,
                            Tipo_pokemon = "Bicho"
                        },
                        new
                        {
                            Id = 10,
                            Tipo_pokemon = "Normal"
                        },
                        new
                        {
                            Id = 11,
                            Tipo_pokemon = "Tierra"
                        },
                        new
                        {
                            Id = 12,
                            Tipo_pokemon = "Lucha"
                        },
                        new
                        {
                            Id = 13,
                            Tipo_pokemon = "Hada"
                        },
                        new
                        {
                            Id = 14,
                            Tipo_pokemon = "Psiquico"
                        },
                        new
                        {
                            Id = 16,
                            Tipo_pokemon = "Dragón"
                        },
                        new
                        {
                            Id = 17,
                            Tipo_pokemon = "Fantasma"
                        },
                        new
                        {
                            Id = 18,
                            Tipo_pokemon = "Siniestro"
                        },
                        new
                        {
                            Id = 19,
                            Tipo_pokemon = "Veneno"
                        });
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.TipoBonus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DebilidadId")
                        .HasColumnType("int");

                    b.Property<int>("EficazId")
                        .HasColumnType("int");

                    b.Property<int>("IdTipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("EficazId", "DebilidadId", "IdTipo");

                    b.HasIndex("DebilidadId");

                    b.ToTable("Bonuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DebilidadId = 2,
                            EficazId = 3,
                            IdTipo = 1
                        },
                        new
                        {
                            Id = 2,
                            DebilidadId = 4,
                            EficazId = 1,
                            IdTipo = 2
                        },
                        new
                        {
                            Id = 3,
                            DebilidadId = 8,
                            EficazId = 11,
                            IdTipo = 2
                        });
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.Tipos_Habilidades", b =>
                {
                    b.Property<int?>("TipoId")
                        .HasColumnType("int");

                    b.Property<int?>("HabilidadId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("TipoId", "HabilidadId");

                    b.HasIndex("HabilidadId");

                    b.ToTable("Tipos_Habilidades");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            HabilidadId = 1,
                            Id = 1
                        },
                        new
                        {
                            TipoId = 2,
                            HabilidadId = 2,
                            Id = 2
                        },
                        new
                        {
                            TipoId = 3,
                            HabilidadId = 3,
                            Id = 3
                        },
                        new
                        {
                            TipoId = 4,
                            HabilidadId = 4,
                            Id = 4
                        },
                        new
                        {
                            TipoId = 4,
                            HabilidadId = 3,
                            Id = 5
                        });
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.Zona", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("NombreZona")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zonas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreZona = "Inicio"
                        },
                        new
                        {
                            Id = 2,
                            NombreZona = "Inicio2"
                        });
                });

            modelBuilder.Entity("PokemonBackend.Models.Entrenador", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Entrenadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Marc"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Dani"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Ernest"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Nicol"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Jose"
                        });
                });

            modelBuilder.Entity("PokemonBackend.Models.Entrenadores_Pokemon", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int?>("EntrenadorId")
                        .HasColumnType("int");

                    b.Property<int?>("PokemonId")
                        .HasColumnType("int");

                    b.Property<bool?>("Shiny")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EntrenadorId");

                    b.HasIndex("PokemonId");

                    b.ToTable("Entrenadores_Pokemons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EntrenadorId = 1,
                            PokemonId = 5
                        },
                        new
                        {
                            Id = 2,
                            EntrenadorId = 2,
                            PokemonId = 6
                        },
                        new
                        {
                            Id = 3,
                            EntrenadorId = 2,
                            PokemonId = 6
                        });
                });

            modelBuilder.Entity("PokemonBackend.Models.Habilidades", b =>
                {
                    b.Property<int?>("HabilidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("HabilidadId"), 1L, 1);

                    b.Property<string>("Habilidad_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Habilidad_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Habilidad_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Habilidad_4")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HabilidadId");

                    b.ToTable("Habilidades");

                    b.HasData(
                        new
                        {
                            HabilidadId = 1,
                            Habilidad_1 = "Placaje",
                            Habilidad_2 = "Ascuas",
                            Habilidad_3 = "Llamarada",
                            Habilidad_4 = "Gruñido"
                        },
                        new
                        {
                            HabilidadId = 2,
                            Habilidad_1 = "Placaje",
                            Habilidad_2 = "Pistola Agua",
                            Habilidad_3 = "Surf",
                            Habilidad_4 = "Ataque arena"
                        },
                        new
                        {
                            HabilidadId = 3,
                            Habilidad_1 = "Placaje",
                            Habilidad_2 = "Latigo cepa",
                            Habilidad_3 = "Hoja afilada",
                            Habilidad_4 = "Ataque arena"
                        },
                        new
                        {
                            HabilidadId = 4,
                            Habilidad_1 = "Placaje",
                            Habilidad_2 = "Impactrueno",
                            Habilidad_3 = "Rayo",
                            Habilidad_4 = "Trueno"
                        });
                });

            modelBuilder.Entity("PokemonBackend.Models.PokedexTipo", b =>
                {
                    b.Property<int?>("PokedexId")
                        .HasColumnType("int");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("PokedexId", "TipoId");

                    b.HasIndex("TipoId");

                    b.ToTable("Tipo_Pokemons");

                    b.HasData(
                        new
                        {
                            PokedexId = 1,
                            TipoId = 3,
                            Id = 1
                        },
                        new
                        {
                            PokedexId = 1,
                            TipoId = 19,
                            Id = 2
                        },
                        new
                        {
                            PokedexId = 2,
                            TipoId = 3,
                            Id = 3
                        },
                        new
                        {
                            PokedexId = 2,
                            TipoId = 19,
                            Id = 4
                        },
                        new
                        {
                            PokedexId = 3,
                            TipoId = 3,
                            Id = 5
                        },
                        new
                        {
                            PokedexId = 3,
                            TipoId = 19,
                            Id = 6
                        },
                        new
                        {
                            PokedexId = 4,
                            TipoId = 1,
                            Id = 7
                        },
                        new
                        {
                            PokedexId = 5,
                            TipoId = 1,
                            Id = 8
                        },
                        new
                        {
                            PokedexId = 6,
                            TipoId = 1,
                            Id = 9
                        },
                        new
                        {
                            PokedexId = 6,
                            TipoId = 7,
                            Id = 10
                        },
                        new
                        {
                            PokedexId = 7,
                            TipoId = 2,
                            Id = 11
                        },
                        new
                        {
                            PokedexId = 8,
                            TipoId = 2,
                            Id = 12
                        },
                        new
                        {
                            PokedexId = 9,
                            TipoId = 2,
                            Id = 13
                        },
                        new
                        {
                            PokedexId = 10,
                            TipoId = 9,
                            Id = 14
                        },
                        new
                        {
                            PokedexId = 11,
                            TipoId = 9,
                            Id = 15
                        },
                        new
                        {
                            PokedexId = 12,
                            TipoId = 9,
                            Id = 16
                        },
                        new
                        {
                            PokedexId = 12,
                            TipoId = 7,
                            Id = 17
                        },
                        new
                        {
                            PokedexId = 13,
                            TipoId = 7,
                            Id = 18
                        },
                        new
                        {
                            PokedexId = 13,
                            TipoId = 19,
                            Id = 19
                        },
                        new
                        {
                            PokedexId = 14,
                            TipoId = 7,
                            Id = 20
                        },
                        new
                        {
                            PokedexId = 14,
                            TipoId = 19,
                            Id = 21
                        },
                        new
                        {
                            PokedexId = 15,
                            TipoId = 7,
                            Id = 22
                        },
                        new
                        {
                            PokedexId = 15,
                            TipoId = 19,
                            Id = 23
                        },
                        new
                        {
                            PokedexId = 16,
                            TipoId = 7,
                            Id = 24
                        },
                        new
                        {
                            PokedexId = 16,
                            TipoId = 10,
                            Id = 25
                        },
                        new
                        {
                            PokedexId = 17,
                            TipoId = 7,
                            Id = 26
                        },
                        new
                        {
                            PokedexId = 17,
                            TipoId = 10,
                            Id = 27
                        },
                        new
                        {
                            PokedexId = 18,
                            TipoId = 7,
                            Id = 28
                        },
                        new
                        {
                            PokedexId = 18,
                            TipoId = 10,
                            Id = 29
                        },
                        new
                        {
                            PokedexId = 19,
                            TipoId = 10,
                            Id = 30
                        },
                        new
                        {
                            PokedexId = 20,
                            TipoId = 10,
                            Id = 31
                        },
                        new
                        {
                            PokedexId = 21,
                            TipoId = 10,
                            Id = 32
                        },
                        new
                        {
                            PokedexId = 21,
                            TipoId = 7,
                            Id = 33
                        },
                        new
                        {
                            PokedexId = 22,
                            TipoId = 7,
                            Id = 34
                        },
                        new
                        {
                            PokedexId = 22,
                            TipoId = 10,
                            Id = 35
                        },
                        new
                        {
                            PokedexId = 23,
                            TipoId = 19,
                            Id = 36
                        },
                        new
                        {
                            PokedexId = 24,
                            TipoId = 19,
                            Id = 37
                        },
                        new
                        {
                            PokedexId = 25,
                            TipoId = 4,
                            Id = 38
                        },
                        new
                        {
                            PokedexId = 26,
                            TipoId = 4,
                            Id = 39
                        },
                        new
                        {
                            PokedexId = 27,
                            TipoId = 11,
                            Id = 40
                        },
                        new
                        {
                            PokedexId = 28,
                            TipoId = 11,
                            Id = 41
                        },
                        new
                        {
                            PokedexId = 29,
                            TipoId = 19,
                            Id = 42
                        },
                        new
                        {
                            PokedexId = 30,
                            TipoId = 19,
                            Id = 43
                        },
                        new
                        {
                            PokedexId = 31,
                            TipoId = 19,
                            Id = 44
                        },
                        new
                        {
                            PokedexId = 31,
                            TipoId = 11,
                            Id = 45
                        },
                        new
                        {
                            PokedexId = 32,
                            TipoId = 19,
                            Id = 46
                        },
                        new
                        {
                            PokedexId = 33,
                            TipoId = 19,
                            Id = 47
                        },
                        new
                        {
                            PokedexId = 34,
                            TipoId = 19,
                            Id = 48
                        },
                        new
                        {
                            PokedexId = 34,
                            TipoId = 11,
                            Id = 49
                        },
                        new
                        {
                            PokedexId = 35,
                            TipoId = 13,
                            Id = 50
                        },
                        new
                        {
                            PokedexId = 36,
                            TipoId = 13,
                            Id = 51
                        },
                        new
                        {
                            PokedexId = 37,
                            TipoId = 1,
                            Id = 52
                        },
                        new
                        {
                            PokedexId = 38,
                            TipoId = 1,
                            Id = 53
                        });
                });

            modelBuilder.Entity("PokemonBackend.Models.Pokemon", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PokedexId")
                        .HasColumnType("int");

                    b.Property<bool?>("Shiny")
                        .HasColumnType("bit");

                    b.Property<int?>("StatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokedexId");

                    b.HasIndex("StatId");

                    b.ToTable("Pokemons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nivel = 0,
                            PokedexId = 1
                        },
                        new
                        {
                            Id = 2,
                            Nivel = 0,
                            PokedexId = 4
                        },
                        new
                        {
                            Id = 3,
                            Nivel = 0,
                            PokedexId = 2
                        },
                        new
                        {
                            Id = 4,
                            Nivel = 0,
                            PokedexId = 5
                        },
                        new
                        {
                            Id = 5,
                            Nivel = 0,
                            PokedexId = 100
                        },
                        new
                        {
                            Id = 6,
                            Nivel = 0,
                            PokedexId = 25
                        });
                });

            modelBuilder.Entity("PokemonBackend.Models.Stat", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int?>("Ataque")
                        .HasColumnType("int");

                    b.Property<int?>("Defensa")
                        .HasColumnType("int");

                    b.Property<int?>("Nivel")
                        .HasColumnType("int");

                    b.Property<int?>("Vida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ataque = 15,
                            Defensa = 10,
                            Nivel = 20,
                            Vida = 40
                        });
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.Debilidades", b =>
                {
                    b.HasOne("Acceso_BD.Repository.Entity.Tipo", "BonusDeb")
                        .WithMany("Debilidades")
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonusDeb");
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.Fortalezas", b =>
                {
                    b.HasOne("Acceso_BD.Repository.Entity.Tipo", "BonusEf")
                        .WithMany("Fortalezas")
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonusEf");
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.ModificadorTipo", b =>
                {
                    b.HasOne("Acceso_BD.Repository.Entity.Tipo", "Bonus")
                        .WithMany()
                        .HasForeignKey("BonusId");

                    b.Navigation("Bonus");
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.Pokedex", b =>
                {
                    b.HasOne("Acceso_BD.Repository.Entity.Region", "Region")
                        .WithMany("Pokedex")
                        .HasForeignKey("RegionId");

                    b.HasOne("PokemonBackend.Models.Stat", null)
                        .WithMany("Pokedex")
                        .HasForeignKey("StatId");

                    b.HasOne("Acceso_BD.Repository.Entity.Tier", "Tier")
                        .WithOne("Pokedex")
                        .HasForeignKey("Acceso_BD.Repository.Entity.Pokedex", "TierId");

                    b.HasOne("Acceso_BD.Repository.Entity.Zona", "Zona")
                        .WithMany("Pokedex")
                        .HasForeignKey("ZonaId");

                    b.Navigation("Region");

                    b.Navigation("Tier");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.TipoBonus", b =>
                {
                    b.HasOne("Acceso_BD.Repository.Entity.Tipo", "BonusDeb")
                        .WithMany("Bonus")
                        .HasForeignKey("DebilidadId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Acceso_BD.Repository.Entity.Tipo", "BonusEf")
                        .WithMany("Bonuses")
                        .HasForeignKey("EficazId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BonusDeb");

                    b.Navigation("BonusEf");
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.Tipos_Habilidades", b =>
                {
                    b.HasOne("PokemonBackend.Models.Habilidades", "Habilidades")
                        .WithMany("habilidades_tipos")
                        .HasForeignKey("HabilidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Acceso_BD.Repository.Entity.Tipo", "Tipo")
                        .WithMany("Habilidades_tipos")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidades");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("PokemonBackend.Models.Entrenadores_Pokemon", b =>
                {
                    b.HasOne("PokemonBackend.Models.Entrenador", "Entrenador")
                        .WithMany("Entrenador_Pokemons")
                        .HasForeignKey("EntrenadorId");

                    b.HasOne("PokemonBackend.Models.Pokemon", "Pokemon")
                        .WithMany("Entrenador_Pokemons")
                        .HasForeignKey("PokemonId");

                    b.Navigation("Entrenador");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokemonBackend.Models.PokedexTipo", b =>
                {
                    b.HasOne("Acceso_BD.Repository.Entity.Pokedex", "Pokedex")
                        .WithMany("PokedexTipos")
                        .HasForeignKey("PokedexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Acceso_BD.Repository.Entity.Tipo", "Tipo")
                        .WithMany("PokedexTipos")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokedex");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("PokemonBackend.Models.Pokemon", b =>
                {
                    b.HasOne("Acceso_BD.Repository.Entity.Pokedex", "Pokedex")
                        .WithMany("Pokemons")
                        .HasForeignKey("PokedexId");

                    b.HasOne("PokemonBackend.Models.Stat", "Stat")
                        .WithMany("Pokemons")
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Pokedex");

                    b.Navigation("Stat");
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.Pokedex", b =>
                {
                    b.Navigation("PokedexTipos");

                    b.Navigation("Pokemons");
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.Region", b =>
                {
                    b.Navigation("Pokedex");
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.Tier", b =>
                {
                    b.Navigation("Pokedex");
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.Tipo", b =>
                {
                    b.Navigation("Bonus");

                    b.Navigation("Bonuses");

                    b.Navigation("Debilidades");

                    b.Navigation("Fortalezas");

                    b.Navigation("Habilidades_tipos");

                    b.Navigation("PokedexTipos");
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.Zona", b =>
                {
                    b.Navigation("Pokedex");
                });

            modelBuilder.Entity("PokemonBackend.Models.Entrenador", b =>
                {
                    b.Navigation("Entrenador_Pokemons");
                });

            modelBuilder.Entity("PokemonBackend.Models.Habilidades", b =>
                {
                    b.Navigation("habilidades_tipos");
                });

            modelBuilder.Entity("PokemonBackend.Models.Pokemon", b =>
                {
                    b.Navigation("Entrenador_Pokemons");
                });

            modelBuilder.Entity("PokemonBackend.Models.Stat", b =>
                {
                    b.Navigation("Pokedex");

                    b.Navigation("Pokemons");
                });
#pragma warning restore 612, 618
        }
    }
}
