// <auto-generated />
using System;
using Data_Acces_Layer.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PokemonBackend.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220726080815_AddNuevosPokemonsTipos")]
    partial class AddNuevosPokemonsTipos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Acceso_BD.Repository.Entity.Pokedex", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("ID"), 1L, 1);

                    b.Property<string>("Altura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Peso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StatId");

                    b.ToTable("Pokedex");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Nombre = "Bulbasaur"
                        },
                        new
                        {
                            ID = 2,
                            Nombre = "Ivysaur"
                        },
                        new
                        {
                            ID = 3,
                            Nombre = "Venasaur"
                        },
                        new
                        {
                            ID = 4,
                            Nombre = "Charmander"
                        },
                        new
                        {
                            ID = 5,
                            Nombre = "Charmeleon"
                        },
                        new
                        {
                            ID = 6,
                            Nombre = "Charizard "
                        },
                        new
                        {
                            ID = 7,
                            Nombre = "Squirtle "
                        },
                        new
                        {
                            ID = 8,
                            Nombre = "Wartotle"
                        },
                        new
                        {
                            ID = 9,
                            Nombre = "Blastoise"
                        },
                        new
                        {
                            ID = 10,
                            Nombre = "Caterpie"
                        },
                        new
                        {
                            ID = 11,
                            Nombre = "Metapod"
                        },
                        new
                        {
                            ID = 12,
                            Nombre = "Butterfree"
                        },
                        new
                        {
                            ID = 13,
                            Nombre = "Weedle"
                        },
                        new
                        {
                            ID = 14,
                            Nombre = "Kakuna"
                        },
                        new
                        {
                            ID = 15,
                            Nombre = "Beedril"
                        },
                        new
                        {
                            ID = 16,
                            Nombre = "Pidgey"
                        },
                        new
                        {
                            ID = 17,
                            Nombre = "Pidgeotto"
                        },
                        new
                        {
                            ID = 18,
                            Nombre = "Pidgeot"
                        },
                        new
                        {
                            ID = 19,
                            Nombre = "Rattata"
                        },
                        new
                        {
                            ID = 20,
                            Nombre = "Raticat"
                        },
                        new
                        {
                            ID = 21,
                            Nombre = "Spearow"
                        },
                        new
                        {
                            ID = 22,
                            Nombre = "Fearow"
                        },
                        new
                        {
                            ID = 23,
                            Nombre = "Ekans"
                        },
                        new
                        {
                            ID = 24,
                            Nombre = "Arbok"
                        },
                        new
                        {
                            ID = 25,
                            Nombre = "Pikachu"
                        },
                        new
                        {
                            ID = 26,
                            Nombre = "Raichu"
                        },
                        new
                        {
                            ID = 27,
                            Nombre = "Sandshrew"
                        },
                        new
                        {
                            ID = 28,
                            Nombre = "Sandslah"
                        },
                        new
                        {
                            ID = 29,
                            Nombre = "Nidoran ♀"
                        },
                        new
                        {
                            ID = 30,
                            Nombre = "Nidorina"
                        },
                        new
                        {
                            ID = 31,
                            Nombre = "Nidoqueen"
                        },
                        new
                        {
                            ID = 32,
                            Nombre = "Nidoran ♂"
                        },
                        new
                        {
                            ID = 33,
                            Nombre = "Nidorino"
                        },
                        new
                        {
                            ID = 34,
                            Nombre = "Nidoking"
                        },
                        new
                        {
                            ID = 35,
                            Nombre = "Clefairy"
                        },
                        new
                        {
                            ID = 36,
                            Nombre = "Clefable"
                        },
                        new
                        {
                            ID = 37,
                            Nombre = "Vulpix"
                        },
                        new
                        {
                            ID = 38,
                            Nombre = "Ninetales"
                        },
                        new
                        {
                            ID = 39,
                            Nombre = "Jigglypuff"
                        },
                        new
                        {
                            ID = 40,
                            Nombre = "Wigglytuff"
                        },
                        new
                        {
                            ID = 41,
                            Nombre = "Zubat"
                        },
                        new
                        {
                            ID = 42,
                            Nombre = "Golbat"
                        },
                        new
                        {
                            ID = 43,
                            Nombre = "Oddish"
                        },
                        new
                        {
                            ID = 44,
                            Nombre = "Gloom"
                        },
                        new
                        {
                            ID = 45,
                            Nombre = "Vileplume"
                        },
                        new
                        {
                            ID = 46,
                            Nombre = "Paras"
                        },
                        new
                        {
                            ID = 47,
                            Nombre = "Parasect"
                        },
                        new
                        {
                            ID = 48,
                            Nombre = "Venonat"
                        },
                        new
                        {
                            ID = 49,
                            Nombre = "Venomoth"
                        },
                        new
                        {
                            ID = 50,
                            Nombre = "Diglett"
                        },
                        new
                        {
                            ID = 51,
                            Nombre = "Dugtrio"
                        },
                        new
                        {
                            ID = 52,
                            Nombre = "Meowth"
                        },
                        new
                        {
                            ID = 53,
                            Nombre = "Persian"
                        },
                        new
                        {
                            ID = 54,
                            Nombre = "Psyduck"
                        },
                        new
                        {
                            ID = 55,
                            Nombre = "Golduck"
                        },
                        new
                        {
                            ID = 56,
                            Nombre = "Mankey"
                        },
                        new
                        {
                            ID = 57,
                            Nombre = "Primeape"
                        },
                        new
                        {
                            ID = 58,
                            Nombre = "Growlithe"
                        },
                        new
                        {
                            ID = 59,
                            Nombre = "Arcanine"
                        },
                        new
                        {
                            ID = 60,
                            Nombre = "Poliwag"
                        },
                        new
                        {
                            ID = 61,
                            Nombre = "Poliwhirl"
                        },
                        new
                        {
                            ID = 62,
                            Nombre = "Poliwrath"
                        },
                        new
                        {
                            ID = 63,
                            Nombre = "Abra"
                        },
                        new
                        {
                            ID = 64,
                            Nombre = "Kadabra"
                        },
                        new
                        {
                            ID = 65,
                            Nombre = "Alakazam"
                        },
                        new
                        {
                            ID = 66,
                            Nombre = "Machop"
                        },
                        new
                        {
                            ID = 67,
                            Nombre = "Machoke"
                        },
                        new
                        {
                            ID = 68,
                            Nombre = "Machamp"
                        },
                        new
                        {
                            ID = 69,
                            Nombre = "Bellsprout"
                        },
                        new
                        {
                            ID = 70,
                            Nombre = "Weepinbell"
                        },
                        new
                        {
                            ID = 71,
                            Nombre = "Victreebell"
                        },
                        new
                        {
                            ID = 72,
                            Nombre = "Tentacool"
                        },
                        new
                        {
                            ID = 73,
                            Nombre = "Tentacruel"
                        },
                        new
                        {
                            ID = 74,
                            Nombre = "Geodude"
                        },
                        new
                        {
                            ID = 75,
                            Nombre = "Graveler"
                        },
                        new
                        {
                            ID = 76,
                            Nombre = "Golem"
                        },
                        new
                        {
                            ID = 77,
                            Nombre = "Ponyta"
                        },
                        new
                        {
                            ID = 78,
                            Nombre = "Rapidash"
                        },
                        new
                        {
                            ID = 79,
                            Nombre = "Slowpoke"
                        },
                        new
                        {
                            ID = 80,
                            Nombre = "Slowbro"
                        },
                        new
                        {
                            ID = 81,
                            Nombre = "Magnemite"
                        },
                        new
                        {
                            ID = 82,
                            Nombre = "Magneton"
                        },
                        new
                        {
                            ID = 83,
                            Nombre = "Farfetch'd"
                        },
                        new
                        {
                            ID = 84,
                            Nombre = "Doduo"
                        },
                        new
                        {
                            ID = 85,
                            Nombre = "Dodrio"
                        },
                        new
                        {
                            ID = 86,
                            Nombre = "Seel"
                        },
                        new
                        {
                            ID = 87,
                            Nombre = "Dewgong"
                        },
                        new
                        {
                            ID = 88,
                            Nombre = "Grimer"
                        },
                        new
                        {
                            ID = 89,
                            Nombre = "Muk"
                        },
                        new
                        {
                            ID = 90,
                            Nombre = "Shellder"
                        },
                        new
                        {
                            ID = 91,
                            Nombre = "Cloyster"
                        },
                        new
                        {
                            ID = 92,
                            Nombre = "Gastly"
                        },
                        new
                        {
                            ID = 93,
                            Nombre = "Haunter"
                        },
                        new
                        {
                            ID = 94,
                            Nombre = "Gengar"
                        },
                        new
                        {
                            ID = 95,
                            Nombre = "Onix"
                        },
                        new
                        {
                            ID = 96,
                            Nombre = "Drowzee"
                        },
                        new
                        {
                            ID = 97,
                            Nombre = "Hypno"
                        },
                        new
                        {
                            ID = 98,
                            Nombre = "Krabby"
                        },
                        new
                        {
                            ID = 99,
                            Nombre = "Kingler"
                        },
                        new
                        {
                            ID = 100,
                            Nombre = "Voltorb"
                        });
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.Tipos_Habilidades", b =>
                {
                    b.Property<int?>("TipoId")
                        .HasColumnType("int");

                    b.Property<int?>("HabilidadId")
                        .HasColumnType("int");

                    b.HasKey("TipoId", "HabilidadId");

                    b.HasIndex("HabilidadId");

                    b.ToTable("Tipos_Habilidades");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            HabilidadId = 1
                        },
                        new
                        {
                            TipoId = 2,
                            HabilidadId = 2
                        },
                        new
                        {
                            TipoId = 3,
                            HabilidadId = 3
                        },
                        new
                        {
                            TipoId = 4,
                            HabilidadId = 4
                        });
                });

            modelBuilder.Entity("PokemonBackend.Models.Entrenador", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Entrenadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Marc"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Dani"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Ernest"
                        });
                });

            modelBuilder.Entity("PokemonBackend.Models.Entrenadores_Pokemon", b =>
                {
                    b.Property<int?>("EntrenadorId")
                        .HasColumnType("int");

                    b.Property<int?>("PokemonId")
                        .HasColumnType("int");

                    b.HasKey("EntrenadorId", "PokemonId");

                    b.HasIndex("PokemonId");

                    b.ToTable("Entrenadores_Pokemons");

                    b.HasData(
                        new
                        {
                            EntrenadorId = 2,
                            PokemonId = 4
                        },
                        new
                        {
                            EntrenadorId = 1,
                            PokemonId = 4
                        },
                        new
                        {
                            EntrenadorId = 3,
                            PokemonId = 5
                        });
                });

            modelBuilder.Entity("PokemonBackend.Models.Habilidades", b =>
                {
                    b.Property<int?>("HabilidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("HabilidadId"), 1L, 1);

                    b.Property<string>("Habilidad_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Habilidad_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Habilidad_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Habilidad_4")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HabilidadId");

                    b.ToTable("Habilidades");

                    b.HasData(
                        new
                        {
                            HabilidadId = 1,
                            Habilidad_1 = "Placaje",
                            Habilidad_2 = "Ascuas",
                            Habilidad_3 = "Llamarada",
                            Habilidad_4 = "Gruñido"
                        },
                        new
                        {
                            HabilidadId = 2,
                            Habilidad_1 = "Placaje",
                            Habilidad_2 = "Pistola Agua",
                            Habilidad_3 = "Surf",
                            Habilidad_4 = "Ataque arena"
                        },
                        new
                        {
                            HabilidadId = 3,
                            Habilidad_1 = "Placaje",
                            Habilidad_2 = "Latigo cepa",
                            Habilidad_3 = "Hoja afilada",
                            Habilidad_4 = "Ataque arena"
                        },
                        new
                        {
                            HabilidadId = 4,
                            Habilidad_1 = "Placaje",
                            Habilidad_2 = "Impactrueno",
                            Habilidad_3 = "Rayo",
                            Habilidad_4 = "Trueno"
                        });
                });

            modelBuilder.Entity("PokemonBackend.Models.Pokemon", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int?>("EntrenadorId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Shiny")
                        .HasColumnType("bit");

                    b.Property<int?>("StatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntrenadorId");

                    b.HasIndex("StatId");

                    b.ToTable("Pokemons");
                });

            modelBuilder.Entity("PokemonBackend.Models.Stat", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int?>("Ataque")
                        .HasColumnType("int");

                    b.Property<int?>("Defensa")
                        .HasColumnType("int");

                    b.Property<int?>("Nivel")
                        .HasColumnType("int");

                    b.Property<int?>("Vida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ataque = 15,
                            Defensa = 10,
                            Nivel = 20,
                            Vida = 40
                        });
                });

            modelBuilder.Entity("PokemonBackend.Models.Tipo", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("Debil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eficaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo_pokemon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tipos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Debil = "Agua",
                            Eficaz = "Planta",
                            Tipo_pokemon = "Fuego"
                        },
                        new
                        {
                            Id = 2,
                            Debil = "Planta",
                            Eficaz = "Fuego",
                            Tipo_pokemon = "Agua"
                        },
                        new
                        {
                            Id = 3,
                            Debil = "Fuego",
                            Eficaz = "Agua",
                            Tipo_pokemon = "Planta"
                        },
                        new
                        {
                            Id = 4,
                            Debil = "Dragon",
                            Eficaz = "Agua",
                            Tipo_pokemon = "Electrico"
                        },
                        new
                        {
                            Id = 5,
                            Debil = "Acero",
                            Eficaz = "Fuego",
                            Tipo_pokemon = "Roca"
                        },
                        new
                        {
                            Id = 6,
                            Debil = "",
                            Eficaz = "",
                            Tipo_pokemon = "Acero"
                        },
                        new
                        {
                            Id = 7,
                            Debil = "",
                            Eficaz = "",
                            Tipo_pokemon = "Volador"
                        },
                        new
                        {
                            Id = 8,
                            Debil = "",
                            Eficaz = "",
                            Tipo_pokemon = "Hielo"
                        },
                        new
                        {
                            Id = 9,
                            Debil = "",
                            Eficaz = "",
                            Tipo_pokemon = "Bicho"
                        },
                        new
                        {
                            Id = 10,
                            Debil = "",
                            Eficaz = "",
                            Tipo_pokemon = "Normal"
                        },
                        new
                        {
                            Id = 11,
                            Debil = "",
                            Eficaz = "",
                            Tipo_pokemon = "Tierra"
                        },
                        new
                        {
                            Id = 12,
                            Debil = "",
                            Eficaz = "",
                            Tipo_pokemon = "Lucha"
                        },
                        new
                        {
                            Id = 13,
                            Debil = "",
                            Eficaz = "",
                            Tipo_pokemon = "Hada"
                        },
                        new
                        {
                            Id = 14,
                            Debil = "",
                            Eficaz = "",
                            Tipo_pokemon = "Psiquico"
                        },
                        new
                        {
                            Id = 15,
                            Debil = "",
                            Eficaz = "",
                            Tipo_pokemon = "Veneno"
                        },
                        new
                        {
                            Id = 16,
                            Debil = "",
                            Eficaz = "",
                            Tipo_pokemon = "Dragón"
                        },
                        new
                        {
                            Id = 17,
                            Debil = "",
                            Eficaz = "",
                            Tipo_pokemon = "Fantasma"
                        },
                        new
                        {
                            Id = 18,
                            Debil = "",
                            Eficaz = "",
                            Tipo_pokemon = "Siniestro"
                        });
                });

            modelBuilder.Entity("PokemonBackend.Models.Tipos_Pokemons", b =>
                {
                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.Property<int?>("PokedexId")
                        .HasColumnType("int");

                    b.Property<int?>("PokemonId")
                        .HasColumnType("int");

                    b.HasKey("TipoId", "PokedexId");

                    b.HasIndex("PokedexId");

                    b.HasIndex("PokemonId");

                    b.ToTable("Tipo_Pokemons");

                    b.HasData(
                        new
                        {
                            TipoId = 3,
                            PokedexId = 1
                        });
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.Pokedex", b =>
                {
                    b.HasOne("PokemonBackend.Models.Stat", null)
                        .WithMany("Pokedex")
                        .HasForeignKey("StatId");
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.Tipos_Habilidades", b =>
                {
                    b.HasOne("PokemonBackend.Models.Habilidades", "Habilidades")
                        .WithMany("habilidades_tipos")
                        .HasForeignKey("HabilidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonBackend.Models.Tipo", "Tipo")
                        .WithMany("habilidades_tipos")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidades");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("PokemonBackend.Models.Entrenadores_Pokemon", b =>
                {
                    b.HasOne("PokemonBackend.Models.Entrenador", "Entrenador")
                        .WithMany("Entrenador_Pokemons")
                        .HasForeignKey("EntrenadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonBackend.Models.Pokemon", "Pokemon")
                        .WithMany("Entrenador_Pokemons")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrenador");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokemonBackend.Models.Pokemon", b =>
                {
                    b.HasOne("PokemonBackend.Models.Entrenador", null)
                        .WithMany("Pokemons")
                        .HasForeignKey("EntrenadorId");

                    b.HasOne("PokemonBackend.Models.Stat", "Stat")
                        .WithMany("Pokemons")
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Stat");
                });

            modelBuilder.Entity("PokemonBackend.Models.Tipos_Pokemons", b =>
                {
                    b.HasOne("Acceso_BD.Repository.Entity.Pokedex", "Pokedex")
                        .WithMany("Tipos")
                        .HasForeignKey("PokedexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonBackend.Models.Pokemon", null)
                        .WithMany("Tipos")
                        .HasForeignKey("PokemonId");

                    b.HasOne("PokemonBackend.Models.Tipo", "Tipo")
                        .WithMany("Tipos")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokedex");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.Pokedex", b =>
                {
                    b.Navigation("Tipos");
                });

            modelBuilder.Entity("PokemonBackend.Models.Entrenador", b =>
                {
                    b.Navigation("Entrenador_Pokemons");

                    b.Navigation("Pokemons");
                });

            modelBuilder.Entity("PokemonBackend.Models.Habilidades", b =>
                {
                    b.Navigation("habilidades_tipos");
                });

            modelBuilder.Entity("PokemonBackend.Models.Pokemon", b =>
                {
                    b.Navigation("Entrenador_Pokemons");

                    b.Navigation("Tipos");
                });

            modelBuilder.Entity("PokemonBackend.Models.Stat", b =>
                {
                    b.Navigation("Pokedex");

                    b.Navigation("Pokemons");
                });

            modelBuilder.Entity("PokemonBackend.Models.Tipo", b =>
                {
                    b.Navigation("Tipos");

                    b.Navigation("habilidades_tipos");
                });
#pragma warning restore 612, 618
        }
    }
}
