// <auto-generated />
using System;
using Data_Acces_Layer.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acceso_BD.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220809102240_campoShinyBoolean")]
    partial class campoShinyBoolean
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Acceso_BD.Repository.Entity.Pokedex", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("ID"), 1L, 1);

                    b.Property<string>("Altura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Basico")
                        .HasColumnType("bit");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Peso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatId")
                        .HasColumnType("int");

                    b.Property<int?>("Tier")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StatId");

                    b.ToTable("Pokedex");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Basico = true,
                            Nombre = "Bulbasaur",
                            Tier = 1
                        },
                        new
                        {
                            ID = 2,
                            Basico = false,
                            Nombre = "Ivysaur",
                            Tier = 2
                        },
                        new
                        {
                            ID = 3,
                            Basico = false,
                            Nombre = "Venasaur",
                            Tier = 3
                        },
                        new
                        {
                            ID = 4,
                            Basico = true,
                            Nombre = "Charmander",
                            Tier = 1
                        },
                        new
                        {
                            ID = 5,
                            Basico = false,
                            Nombre = "Charmeleon",
                            Tier = 2
                        },
                        new
                        {
                            ID = 6,
                            Basico = false,
                            Nombre = "Charizard ",
                            Tier = 3
                        },
                        new
                        {
                            ID = 7,
                            Basico = true,
                            Nombre = "Squirtle",
                            Tier = 1
                        },
                        new
                        {
                            ID = 8,
                            Nombre = "Wartotle"
                        },
                        new
                        {
                            ID = 9,
                            Nombre = "Blastoise"
                        },
                        new
                        {
                            ID = 10,
                            Nombre = "Caterpie"
                        },
                        new
                        {
                            ID = 11,
                            Nombre = "Metapod"
                        },
                        new
                        {
                            ID = 12,
                            Nombre = "Butterfree"
                        },
                        new
                        {
                            ID = 13,
                            Nombre = "Weedle"
                        },
                        new
                        {
                            ID = 14,
                            Nombre = "Kakuna"
                        },
                        new
                        {
                            ID = 15,
                            Nombre = "Beedril"
                        },
                        new
                        {
                            ID = 16,
                            Nombre = "Pidgey"
                        },
                        new
                        {
                            ID = 17,
                            Nombre = "Pidgeotto"
                        },
                        new
                        {
                            ID = 18,
                            Nombre = "Pidgeot"
                        },
                        new
                        {
                            ID = 19,
                            Nombre = "Rattata"
                        },
                        new
                        {
                            ID = 20,
                            Nombre = "Raticat"
                        },
                        new
                        {
                            ID = 21,
                            Nombre = "Spearow"
                        },
                        new
                        {
                            ID = 22,
                            Nombre = "Fearow"
                        },
                        new
                        {
                            ID = 23,
                            Nombre = "Ekans"
                        },
                        new
                        {
                            ID = 24,
                            Nombre = "Arbok"
                        },
                        new
                        {
                            ID = 25,
                            Nombre = "Pikachu"
                        },
                        new
                        {
                            ID = 26,
                            Nombre = "Raichu"
                        },
                        new
                        {
                            ID = 27,
                            Nombre = "Sandshrew"
                        },
                        new
                        {
                            ID = 28,
                            Nombre = "Sandslah"
                        },
                        new
                        {
                            ID = 29,
                            Nombre = "Nidoran ♀"
                        },
                        new
                        {
                            ID = 30,
                            Nombre = "Nidorina"
                        },
                        new
                        {
                            ID = 31,
                            Nombre = "Nidoqueen"
                        },
                        new
                        {
                            ID = 32,
                            Nombre = "Nidoran ♂"
                        },
                        new
                        {
                            ID = 33,
                            Nombre = "Nidorino"
                        },
                        new
                        {
                            ID = 34,
                            Nombre = "Nidoking"
                        },
                        new
                        {
                            ID = 35,
                            Nombre = "Clefairy"
                        },
                        new
                        {
                            ID = 36,
                            Nombre = "Clefable"
                        },
                        new
                        {
                            ID = 37,
                            Nombre = "Vulpix"
                        },
                        new
                        {
                            ID = 38,
                            Nombre = "Ninetales"
                        },
                        new
                        {
                            ID = 39,
                            Nombre = "Jigglypuff"
                        },
                        new
                        {
                            ID = 40,
                            Nombre = "Wigglytuff"
                        },
                        new
                        {
                            ID = 41,
                            Nombre = "Zubat"
                        },
                        new
                        {
                            ID = 42,
                            Nombre = "Golbat"
                        },
                        new
                        {
                            ID = 43,
                            Nombre = "Oddish"
                        },
                        new
                        {
                            ID = 44,
                            Nombre = "Gloom"
                        },
                        new
                        {
                            ID = 45,
                            Nombre = "Vileplume"
                        },
                        new
                        {
                            ID = 46,
                            Nombre = "Paras"
                        },
                        new
                        {
                            ID = 47,
                            Nombre = "Parasect"
                        },
                        new
                        {
                            ID = 48,
                            Nombre = "Venonat"
                        },
                        new
                        {
                            ID = 49,
                            Nombre = "Venomoth"
                        },
                        new
                        {
                            ID = 50,
                            Nombre = "Diglett"
                        },
                        new
                        {
                            ID = 51,
                            Nombre = "Dugtrio"
                        },
                        new
                        {
                            ID = 52,
                            Nombre = "Meowth"
                        },
                        new
                        {
                            ID = 53,
                            Nombre = "Persian"
                        },
                        new
                        {
                            ID = 54,
                            Nombre = "Psyduck"
                        },
                        new
                        {
                            ID = 55,
                            Nombre = "Golduck"
                        },
                        new
                        {
                            ID = 56,
                            Nombre = "Mankey"
                        },
                        new
                        {
                            ID = 57,
                            Nombre = "Primeape"
                        },
                        new
                        {
                            ID = 58,
                            Nombre = "Growlithe"
                        },
                        new
                        {
                            ID = 59,
                            Nombre = "Arcanine"
                        },
                        new
                        {
                            ID = 60,
                            Nombre = "Poliwag"
                        },
                        new
                        {
                            ID = 61,
                            Nombre = "Poliwhirl"
                        },
                        new
                        {
                            ID = 62,
                            Nombre = "Poliwrath"
                        },
                        new
                        {
                            ID = 63,
                            Nombre = "Abra"
                        },
                        new
                        {
                            ID = 64,
                            Nombre = "Kadabra"
                        },
                        new
                        {
                            ID = 65,
                            Nombre = "Alakazam"
                        },
                        new
                        {
                            ID = 66,
                            Nombre = "Machop"
                        },
                        new
                        {
                            ID = 67,
                            Nombre = "Machoke"
                        },
                        new
                        {
                            ID = 68,
                            Nombre = "Machamp"
                        },
                        new
                        {
                            ID = 69,
                            Nombre = "Bellsprout"
                        },
                        new
                        {
                            ID = 70,
                            Nombre = "Weepinbell"
                        },
                        new
                        {
                            ID = 71,
                            Nombre = "Victreebell"
                        },
                        new
                        {
                            ID = 72,
                            Nombre = "Tentacool"
                        },
                        new
                        {
                            ID = 73,
                            Nombre = "Tentacruel"
                        },
                        new
                        {
                            ID = 74,
                            Nombre = "Geodude"
                        },
                        new
                        {
                            ID = 75,
                            Nombre = "Graveler"
                        },
                        new
                        {
                            ID = 76,
                            Nombre = "Golem"
                        },
                        new
                        {
                            ID = 77,
                            Nombre = "Ponyta"
                        },
                        new
                        {
                            ID = 78,
                            Nombre = "Rapidash"
                        },
                        new
                        {
                            ID = 79,
                            Nombre = "Slowpoke"
                        },
                        new
                        {
                            ID = 80,
                            Nombre = "Slowbro"
                        },
                        new
                        {
                            ID = 81,
                            Nombre = "Magnemite"
                        },
                        new
                        {
                            ID = 82,
                            Nombre = "Magneton"
                        },
                        new
                        {
                            ID = 83,
                            Nombre = "Farfetch'd"
                        },
                        new
                        {
                            ID = 84,
                            Nombre = "Doduo"
                        },
                        new
                        {
                            ID = 85,
                            Nombre = "Dodrio"
                        },
                        new
                        {
                            ID = 86,
                            Nombre = "Seel"
                        },
                        new
                        {
                            ID = 87,
                            Nombre = "Dewgong"
                        },
                        new
                        {
                            ID = 88,
                            Nombre = "Grimer"
                        },
                        new
                        {
                            ID = 89,
                            Nombre = "Muk"
                        },
                        new
                        {
                            ID = 90,
                            Nombre = "Shellder"
                        },
                        new
                        {
                            ID = 91,
                            Nombre = "Cloyster"
                        },
                        new
                        {
                            ID = 92,
                            Nombre = "Gastly"
                        },
                        new
                        {
                            ID = 93,
                            Nombre = "Haunter"
                        },
                        new
                        {
                            ID = 94,
                            Nombre = "Gengar"
                        },
                        new
                        {
                            ID = 95,
                            Nombre = "Onix"
                        },
                        new
                        {
                            ID = 96,
                            Nombre = "Drowzee"
                        },
                        new
                        {
                            ID = 97,
                            Nombre = "Hypno"
                        },
                        new
                        {
                            ID = 98,
                            Nombre = "Krabby"
                        },
                        new
                        {
                            ID = 99,
                            Nombre = "Kingler"
                        },
                        new
                        {
                            ID = 100,
                            Nombre = "Voltorb"
                        });
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.Tipos_Habilidades", b =>
                {
                    b.Property<int?>("TipoId")
                        .HasColumnType("int");

                    b.Property<int?>("HabilidadId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("TipoId", "HabilidadId");

                    b.HasIndex("HabilidadId");

                    b.ToTable("Tipos_Habilidades");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            HabilidadId = 1,
                            Id = 1
                        },
                        new
                        {
                            TipoId = 2,
                            HabilidadId = 2,
                            Id = 2
                        },
                        new
                        {
                            TipoId = 3,
                            HabilidadId = 3,
                            Id = 3
                        },
                        new
                        {
                            TipoId = 4,
                            HabilidadId = 4,
                            Id = 4
                        },
                        new
                        {
                            TipoId = 4,
                            HabilidadId = 3,
                            Id = 5
                        });
                });

            modelBuilder.Entity("PokemonBackend.Models.Debilidades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DebilidadId")
                        .HasColumnType("int");

                    b.Property<int>("IdTipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdTipo");

                    b.ToTable("Debilidades");
                });

            modelBuilder.Entity("PokemonBackend.Models.Entrenador", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Entrenadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Marc"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Dani"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Ernest"
                        });
                });

            modelBuilder.Entity("PokemonBackend.Models.Entrenadores_Pokemon", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int?>("EntrenadorId")
                        .HasColumnType("int");

                    b.Property<int?>("PokemonId")
                        .HasColumnType("int");

                    b.Property<bool?>("Shiny")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EntrenadorId");

                    b.HasIndex("PokemonId");

                    b.ToTable("Entrenadores_Pokemons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EntrenadorId = 1,
                            PokemonId = 5
                        },
                        new
                        {
                            Id = 2,
                            EntrenadorId = 2,
                            PokemonId = 6
                        },
                        new
                        {
                            Id = 3,
                            EntrenadorId = 2,
                            PokemonId = 6
                        });
                });

            modelBuilder.Entity("PokemonBackend.Models.Fortalezas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EficazId")
                        .HasColumnType("int");

                    b.Property<int>("IdTipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdTipo");

                    b.ToTable("Fortalezas");
                });

            modelBuilder.Entity("PokemonBackend.Models.Habilidades", b =>
                {
                    b.Property<int?>("HabilidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("HabilidadId"), 1L, 1);

                    b.Property<string>("Habilidad_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Habilidad_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Habilidad_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Habilidad_4")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HabilidadId");

                    b.ToTable("Habilidades");

                    b.HasData(
                        new
                        {
                            HabilidadId = 1,
                            Habilidad_1 = "Placaje",
                            Habilidad_2 = "Ascuas",
                            Habilidad_3 = "Llamarada",
                            Habilidad_4 = "Gruñido"
                        },
                        new
                        {
                            HabilidadId = 2,
                            Habilidad_1 = "Placaje",
                            Habilidad_2 = "Pistola Agua",
                            Habilidad_3 = "Surf",
                            Habilidad_4 = "Ataque arena"
                        },
                        new
                        {
                            HabilidadId = 3,
                            Habilidad_1 = "Placaje",
                            Habilidad_2 = "Latigo cepa",
                            Habilidad_3 = "Hoja afilada",
                            Habilidad_4 = "Ataque arena"
                        },
                        new
                        {
                            HabilidadId = 4,
                            Habilidad_1 = "Placaje",
                            Habilidad_2 = "Impactrueno",
                            Habilidad_3 = "Rayo",
                            Habilidad_4 = "Trueno"
                        });
                });

            modelBuilder.Entity("PokemonBackend.Models.ModificadorTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BonusId")
                        .HasColumnType("int");

                    b.Property<int>("IdTipo")
                        .HasColumnType("int");

                    b.Property<int>("Modificador")
                        .HasColumnType("int");

                    b.Property<int>("TipoBonusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BonusId");

                    b.ToTable("Modificadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdTipo = 1,
                            Modificador = 1,
                            TipoBonusId = 2
                        },
                        new
                        {
                            Id = 2,
                            IdTipo = 1,
                            Modificador = 0,
                            TipoBonusId = 3
                        });
                });

            modelBuilder.Entity("PokemonBackend.Models.Pokemon", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PokedexId")
                        .HasColumnType("int");

                    b.Property<bool?>("Shiny")
                        .HasColumnType("bit");

                    b.Property<int?>("StatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokedexId");

                    b.HasIndex("StatId");

                    b.ToTable("Pokemons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nivel = 0,
                            Nombre = "test",
                            PokedexId = 1
                        },
                        new
                        {
                            Id = 2,
                            Nivel = 0,
                            PokedexId = 4
                        },
                        new
                        {
                            Id = 3,
                            Nivel = 0,
                            PokedexId = 2
                        },
                        new
                        {
                            Id = 4,
                            Nivel = 0,
                            PokedexId = 5
                        },
                        new
                        {
                            Id = 5,
                            Nivel = 0,
                            PokedexId = 100
                        },
                        new
                        {
                            Id = 6,
                            Nivel = 0,
                            PokedexId = 25
                        });
                });

            modelBuilder.Entity("PokemonBackend.Models.Stat", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int?>("Ataque")
                        .HasColumnType("int");

                    b.Property<int?>("Defensa")
                        .HasColumnType("int");

                    b.Property<int?>("Nivel")
                        .HasColumnType("int");

                    b.Property<int?>("Vida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ataque = 15,
                            Defensa = 10,
                            Nivel = 20,
                            Vida = 40
                        });
                });

            modelBuilder.Entity("PokemonBackend.Models.Tipo", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("Tipo_pokemon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tipos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Tipo_pokemon = "Fuego"
                        },
                        new
                        {
                            Id = 2,
                            Tipo_pokemon = "Agua"
                        },
                        new
                        {
                            Id = 3,
                            Tipo_pokemon = "Planta"
                        },
                        new
                        {
                            Id = 4,
                            Tipo_pokemon = "Electrico"
                        },
                        new
                        {
                            Id = 5,
                            Tipo_pokemon = "Roca"
                        },
                        new
                        {
                            Id = 6,
                            Tipo_pokemon = "Acero"
                        },
                        new
                        {
                            Id = 7,
                            Tipo_pokemon = "Volador"
                        },
                        new
                        {
                            Id = 8,
                            Tipo_pokemon = "Hielo"
                        },
                        new
                        {
                            Id = 9,
                            Tipo_pokemon = "Bicho"
                        },
                        new
                        {
                            Id = 10,
                            Tipo_pokemon = "Normal"
                        },
                        new
                        {
                            Id = 11,
                            Tipo_pokemon = "Tierra"
                        },
                        new
                        {
                            Id = 12,
                            Tipo_pokemon = "Lucha"
                        },
                        new
                        {
                            Id = 13,
                            Tipo_pokemon = "Hada"
                        },
                        new
                        {
                            Id = 14,
                            Tipo_pokemon = "Psiquico"
                        },
                        new
                        {
                            Id = 16,
                            Tipo_pokemon = "Dragón"
                        },
                        new
                        {
                            Id = 17,
                            Tipo_pokemon = "Fantasma"
                        },
                        new
                        {
                            Id = 18,
                            Tipo_pokemon = "Siniestro"
                        },
                        new
                        {
                            Id = 19,
                            Tipo_pokemon = "Veneno"
                        });
                });

            modelBuilder.Entity("PokemonBackend.Models.TipoBonus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DebilidadId")
                        .HasColumnType("int");

                    b.Property<int>("EficazId")
                        .HasColumnType("int");

                    b.Property<int>("IdTipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("EficazId", "DebilidadId", "IdTipo");

                    b.HasIndex("DebilidadId");

                    b.ToTable("Bonuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DebilidadId = 2,
                            EficazId = 3,
                            IdTipo = 1
                        },
                        new
                        {
                            Id = 2,
                            DebilidadId = 4,
                            EficazId = 1,
                            IdTipo = 2
                        },
                        new
                        {
                            Id = 3,
                            DebilidadId = 8,
                            EficazId = 11,
                            IdTipo = 2
                        });
                });

            modelBuilder.Entity("PokemonBackend.Models.Tipos_Pokemons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("PokedexId")
                        .HasColumnType("int");

                    b.Property<int?>("PokemonId")
                        .HasColumnType("int");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokedexId");

                    b.HasIndex("PokemonId");

                    b.HasIndex("TipoId");

                    b.ToTable("Tipo_Pokemons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PokedexId = 1,
                            TipoId = 3
                        },
                        new
                        {
                            Id = 2,
                            PokedexId = 1,
                            TipoId = 19
                        });
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.Pokedex", b =>
                {
                    b.HasOne("PokemonBackend.Models.Stat", null)
                        .WithMany("Pokedex")
                        .HasForeignKey("StatId");
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.Tipos_Habilidades", b =>
                {
                    b.HasOne("PokemonBackend.Models.Habilidades", "Habilidades")
                        .WithMany("habilidades_tipos")
                        .HasForeignKey("HabilidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonBackend.Models.Tipo", "Tipo")
                        .WithMany("Habilidades_tipos")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidades");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("PokemonBackend.Models.Debilidades", b =>
                {
                    b.HasOne("PokemonBackend.Models.Tipo", "BonusDeb")
                        .WithMany("Debilidades")
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonusDeb");
                });

            modelBuilder.Entity("PokemonBackend.Models.Entrenadores_Pokemon", b =>
                {
                    b.HasOne("PokemonBackend.Models.Entrenador", "Entrenador")
                        .WithMany("Entrenador_Pokemons")
                        .HasForeignKey("EntrenadorId");

                    b.HasOne("PokemonBackend.Models.Pokemon", "Pokemon")
                        .WithMany("Entrenador_Pokemons")
                        .HasForeignKey("PokemonId");

                    b.Navigation("Entrenador");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokemonBackend.Models.Fortalezas", b =>
                {
                    b.HasOne("PokemonBackend.Models.Tipo", "BonusEf")
                        .WithMany("Fortalezas")
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonusEf");
                });

            modelBuilder.Entity("PokemonBackend.Models.ModificadorTipo", b =>
                {
                    b.HasOne("PokemonBackend.Models.Tipo", "Bonus")
                        .WithMany()
                        .HasForeignKey("BonusId");

                    b.Navigation("Bonus");
                });

            modelBuilder.Entity("PokemonBackend.Models.Pokemon", b =>
                {
                    b.HasOne("Acceso_BD.Repository.Entity.Pokedex", "Pokedex")
                        .WithMany("Pokemons")
                        .HasForeignKey("PokedexId");

                    b.HasOne("PokemonBackend.Models.Stat", "Stat")
                        .WithMany("Pokemons")
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Pokedex");

                    b.Navigation("Stat");
                });

            modelBuilder.Entity("PokemonBackend.Models.TipoBonus", b =>
                {
                    b.HasOne("PokemonBackend.Models.Tipo", "BonusDeb")
                        .WithMany("Bonus")
                        .HasForeignKey("DebilidadId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PokemonBackend.Models.Tipo", "BonusEf")
                        .WithMany("Bonuses")
                        .HasForeignKey("EficazId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BonusDeb");

                    b.Navigation("BonusEf");
                });

            modelBuilder.Entity("PokemonBackend.Models.Tipos_Pokemons", b =>
                {
                    b.HasOne("Acceso_BD.Repository.Entity.Pokedex", "Pokedex")
                        .WithMany("Tipos")
                        .HasForeignKey("PokedexId");

                    b.HasOne("PokemonBackend.Models.Pokemon", null)
                        .WithMany("Tipos")
                        .HasForeignKey("PokemonId");

                    b.HasOne("PokemonBackend.Models.Tipo", "Tipo")
                        .WithMany("Tipos")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokedex");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Acceso_BD.Repository.Entity.Pokedex", b =>
                {
                    b.Navigation("Pokemons");

                    b.Navigation("Tipos");
                });

            modelBuilder.Entity("PokemonBackend.Models.Entrenador", b =>
                {
                    b.Navigation("Entrenador_Pokemons");
                });

            modelBuilder.Entity("PokemonBackend.Models.Habilidades", b =>
                {
                    b.Navigation("habilidades_tipos");
                });

            modelBuilder.Entity("PokemonBackend.Models.Pokemon", b =>
                {
                    b.Navigation("Entrenador_Pokemons");

                    b.Navigation("Tipos");
                });

            modelBuilder.Entity("PokemonBackend.Models.Stat", b =>
                {
                    b.Navigation("Pokedex");

                    b.Navigation("Pokemons");
                });

            modelBuilder.Entity("PokemonBackend.Models.Tipo", b =>
                {
                    b.Navigation("Bonus");

                    b.Navigation("Bonuses");

                    b.Navigation("Debilidades");

                    b.Navigation("Fortalezas");

                    b.Navigation("Habilidades_tipos");

                    b.Navigation("Tipos");
                });
#pragma warning restore 612, 618
        }
    }
}
